[package]
name = "se-logger"
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://www.github.com/vali820/se-logger/"
description = "Simple customizable logging crate"
keywords = ["logging"]

[dependencies]
chrono = "0.4.22"
